<?php

namespace APIRestBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * IdeaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class IdeaRepository extends EntityRepository
{



}
