<?php

namespace APIRestBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * VoteIdeaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VoteIdeaRepository extends EntityRepository
{
}
