api_rest:
    resource: "@APIRestBundle/Resources/config/routing.yml"
    prefix:   /

api:
    resource: "@APIBundle/Resources/config/routing.php"
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation
